### ISSUE TITLE
1.5. Hacer prototipo de alta fidelidad (Mobile)

### ISSUE THREAD

**Issue by amappola7** [amappola7/burger-queen-api-client#27]

**Comment by Angie-Santos** [comment]
https://www.figma.com/proto/ZjV0wgf0sei5ChAyhdwIsO/Burguer-Queen---Prototipo-de-Baja-Fidelidad?page-id=0%3A1&node-id=11%3A159&viewport=-8%2C181%2C0.24&scaling=scale-down&starting-point-node-id=11%3A159&show-proto-sidebar=1
