### ISSUE TITLE
1.7. Hacer prototipo de alta fidelidad (Desktop)

### ISSUE THREAD

**Issue by amappola7** [amappola7/burger-queen-api-client#29]

**Comment by Angie-Santos** [comment]
https://www.figma.com/proto/ZjV0wgf0sei5ChAyhdwIsO/Burguer-Queen---Prototipo-de-Baja-Fidelidad?page-id=1%3A3&node-id=23%3A98&viewport=-131%2C299%2C0.14&scaling=scale-down&starting-point-node-id=23%3A98
